### ISSUE TITLE
Can't make purchase in Polygot

### ISSUE THREAD

**Issue by Adam-B0mb** [sjpbailey/Documentation#1]
I can't seem to purchase your nodeserver.   Says there "There are no purchase options available."

**Comment by sjpbailey** [comment]
Sorry about that!
For PIR? Is it up In the Production store?
It is a local node i had up on Production accidentally, then back to local store.
I am almost done testing it and will release it soon.
Okay i learn something new every day 😂 on software.
So i have PIR, Sweeper Robot Vacuum and a Four channel relay.
Its almost ready just added another PIR motion to it.

**Comment by sjpbailey** [comment]
Okay PIR motion is on the Production store.
Enjoy

**Comment by sjpbailey** [comment]
Please Let me know if you can see it and i will close this issue.

**Comment by Adam-B0mb** [comment]
Hi Steve,
               Still the same issue I initially reported.
Thanks
Adam

**Comment by sjpbailey** [comment]
Adam can you provide a link to where you are trying to install from please.
I have them up with one purchase option i have no idea why you cannot install it?
I have them all installed on my Eisy system this afternoon. I have not edited a thing.
Have you installed Tuya and your trying to install TuyaPir?
Thank you for your time.

**Comment by Adam-B0mb** [comment]
Just trying to install from the production store.
Steve Bailey
python3
2023-07-01 07:11
June 30th 2023, This has been updated please try a reinstall reboot your Eisy if using UDI phone app. This will be Updated once more for RGB color and Dimmer adjustment while in color. Tuya Tested with TreatLife brand LED's and Switches please see More Info install link. LED Bulbs, Light Strips, Switches and Dimmers should function with a Your Tuya Api Account you setup. This is for Lights, LED Bulbs and Switches. Devices Adds: 1. June 26, 2023 DayBetter Smart Bulb 2. Overhaul LED Bulbs till RGB
None

**Comment by sjpbailey** [comment]
Adam,
Try it again please there was a problem with it. I just updated the purchase options and installed it.

**Comment by sjpbailey** [comment]
Going to update some things and re-install it.

**Comment by Adam-B0mb** [comment]
No change

**Comment by sjpbailey** [comment]
Interesting both pir and robot sweeper would not install until updating purchase option's didn't change a thing. So who knows when i put them up what happened. Anyway it should work now just tried two successful installs of all four.

**Comment by sjpbailey** [comment]
Refresh your store also please

**Comment by Adam-B0mb** [comment]
Tried the refresh with no change.  Don’t’ sweat it for just me.   I am not sure Tuya will support my device anyway so may go another direction anyway…
Adam

**Comment by sjpbailey** [comment]
Okay found two with problems and i just had to update purchase options.
Just installed all three times, once on each of my two Polisy' and once on my Eisy. So if it is sitting there dead uninstall it completely then reinstall it like its the first time.

**Comment by sjpbailey** [comment]
Thank you Adam

**Comment by sjpbailey** [comment]
No problem sorry for the mishap what device do you have? Maybe i build you a non-production free node for? To test?Sent from my iPhoneOn Jul 4, 2023, at 3:58 PM, Adam-B0mb ***@***.***> wrote:﻿
Tried the refresh with no change.  Don’t’ sweat it for just me.   I am not sure Tuya will support my device anyway so may go another direction anyway…

Adam



From: Steven Bailey ***@***.***>

Sent: Tuesday, July 4, 2023 4:53 PM

To: sjpbailey/Documentation ***@***.***>

Cc: Adam Getchell ***@***.***>; Author ***@***.***>

Subject: Re: [sjpbailey/Documentation] Can't make purchase in Polygot (Issue #1)





Refresh your store also please

**Comment by Adam-B0mb** [comment]
My device is PETLIBRO Automatic Cat Feeder ( https://www.amazon.com/dp/B09BJDNZJ5?psc=1&ref=ppx_yo2ov_dt_b_product_details) although I use it for my dog. 😊   I read in a forum that someone got a Petlibro to work but I don’t believe my device is supported.   Happy to help you debug your issues if you need to help.  Just didn’t want you to spend time just for me.
Adam

**Comment by Adam-B0mb** [comment]
Fyi – tired to initiate the purchase of the Tuyasweeper and it worked fine.  Something funny with “Tuya”

**Comment by sjpbailey** [comment]
Are you able to pull it up on Tuya smart app?
 You also have to have an API on Tuya  to get these node servers to work.

 With that i would need a way of getting status information from the device. 
 This would require a temporary use of your credentials for your Tuya API so i can call the device.
 If we get a Json response we can can probably build you a node server.
Email me directly @ sjpbailey@comcast.net if you want to give it go.
Then through the cloud you can watch it work while i control or get a status from it probably for a cleaning.
